package io.rezoome.manager.property;

public enum PropertyEnum {
  
  // AGENCY DAO 
  DAO_CLASS_NAME,
  // AGENCY MAPPER
  MAPPER_CLASS_NAME,
  
  // Job
  THREAD_POOL_CAPAVILITY,

  // DB 
  DBMS_TYPE,
  DBMS_VERSION,
  DB_HOST,
  DB_PORT,
  DB_NAME,
  DB_USER_ID,
  DB_PASSWORD,
  DB_MAX_CONNECTION,
  DB_INIT_CONNECTION,
  DB_MAX_WAIT,
  CONNECTION_POOL_NAME,
  
  
  // AMQ
  AMAZONE_QUEUE_NAME,
  AMAZONE_SERVER_HOST,
  AMAZONE_USER_NAME,
  AMAZONE_USER_PASSWORD,
  
  // Mybatis
  MYBATIS_CONFIG_FILE_PATH
  
  }
