package io.rezoome.manager.property;

public enum PropertyEnum {

  // AGENCY DAO
  DAO_CLASS_NAME, DAO_MAPPER_CLASS_NAME,

  // AGENCY MAPPER
  MAPPER_CLASS_NAME,
  
  // AGENCY PROPERTIES
  PROP_CLASS_NAME,

  // Job
  THREAD_POOL_CAPAVILITY, HEALTH_CHECK_INTERVAL,

  // DB
  DBMS_TYPE, DBMS_VERSION, DB_HOST, DB_PORT, DB_NAME, DB_USER_ID, DB_PASSWORD, DB_MAX_CONNECTION, DB_INIT_CONNECTION, DB_MAX_WAIT, CONNECTION_POOL_NAME,

  // AMQ
  AMAZONE_QUEUE_NAME, AMAZONE_SERVER_HOST, AMAZONE_USER_NAME, AMAZONE_USER_PASSWORD,

  // Mybatis
  MYBATIS_CONFIG_FILE_PATH,

  // Job
  JOB_TEMP_FILE_PATH,

  // Status Manager
  KEEP_ALIVE_SEND_TIME, LIMIT_ALLOW_NOT_SIGNAL_NUMBER, IS_KILL_AGENT,

  // Http
  PORTAL_URL, CONNECT_TIMEOUT, READ_TIMEOUT, RETRIES, RETRY_DELAY_SEC,

  // GENERAL
  ORG_CODE, ORG_NAME, ORG_PASSCODE,

  // AGENT_CERTIFICATION
  KEYSTORE_LOCATION , CERT_NAME , ISSUER_DN , CERT_PASSWORD

}
